#!/usr/bin/env python

import rospy
from uav_gazebo_msgs.msg import PositionYawControl
import math


if __name__ == '__main__':
    rospy.init_node("drone_control", anonymous=True)
    cmd = PositionYawControl()
    pub = rospy.Publisher("drone/position_yaw/command", PositionYawControl, queue_size=1)

    dt = 0.01
    t = 0.
    rate = rospy.Rate(1./dt)
    w = 0.1

    while not rospy.is_shutdown():
        cmd.position.x = math.cos(w*t)
        cmd.position.y = math.sin(w*t)
        cmd.position.z = 1
        cmd.velocity.x = -w*math.sin(w*t)
        cmd.velocity.y = w*math.cos(w*t)
        cmd.yaw = w*t
        cmd.yaw_rate = w
        pub.publish(cmd)
        t += dt
        rate.sleep()
